### ISSUE TITLE
missing file '@/app/lib/langserve-adapter'

### ISSUE THREAD

**Issue by SebastianSong** [hminle/langserve-assistant-ui#1]
Hello. I encountered a "module not found" error while testing your project.
Could you please check and add the missing module? Thank you!
<img width="965" alt="스크린샷 2024-11-14 오전 10 48 38" src="https://github.com/user-attachments/assets/a3603850-8614-4945-b306-5dacf65ca9f9">

**Comment by hminle** [comment]
Hi @SebastianSong , please check out the latest commit, I've just pushed it. Sorry, it's an issue with gitignore.
